apps/company/urls.py
from django.urls import path
from . import views

app_name = "company"

urlpatterns = [
    path("", views.home, name='home'),
    path("dashboard/", views.dashboard, name='dashboard')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.company.urls"))
]

apps/authentication/models.py
from django.db import models

# Create your models here.

apps/company/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
	pass

# create portfolio section
class Portfolio(models.Model):
	class Meta:
		verbose_name = "Porfolio"
		verbose_name_plural = "My Porfolio"

	portfolio_image = models.ImageField(upload_to="portfolio")
	portfolio_heading = models.CharField(max_length=100)
	portfolio_subheading = models.CharField(max_length=100)

	def __str__(self):
		return self.portfolio_heading

# courses category
class Category_courses(models.Model):

	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


# create contact us model
class Contact(models.Model):
    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Apply"

    full_name = models.CharField(max_length=100)
    own_phone = models.IntegerField(default=998)
    extra_phone = models.IntegerField(default=998)
    message = models.CharField(max_length=120)
    category = models.ForeignKey(Category_courses, null=True, default=None, on_delete=models.CASCADE, related_name="category_contact")

    def __str__(self):
        return self.full_name

apps/company/forms.py
from django import forms
from .models import Contact


class ApplyModelForm(forms.ModelForm):

	class Meta:
		model = Contact
		fields = (
			 "full_name",
			 "own_phone",
			 "extra_phone",
			 "message",
			 "category"
			)

apps/authentication/views.py
from django.shortcuts import render

# Create your views here.

apps/company/views.py
from django.shortcuts import render, redirect
from . import models
from .forms import ApplyModelForm

def home(request):
    portfolios = models.Portfolio.objects.all().order_by('id')[:5]
    if request.method == "POST":
        form = ApplyModelForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("/")
    else:
        form = ApplyModelForm()
    return render(request, 'pages/home.html', {"portfolios": portfolios, "form": form})


def dashboard(request):
    contact = models.Contact.objects.all()
    context = {
        "contact": contact
    }
    return render(request, 'pages/dashboard.html', context)

templates/includes/about.html
{% load static %}
<section class="section-padding pb-0" id="about">
  <div class="container mb-5 pb-lg-5">
    <div class="row">
      <div class="col-12">
        <h2 class="mb-3" data-aos="fade-up">Assalomu Aleykum</h2>
      </div>

      <div class="col-lg-6 col-12 mt-3 mb-lg-5">
        <p class="me-4" data-aos="fade-up" data-aos-delay="300">
          You may contribute
          <a rel="nofollow" href="http://paypal.me/templatemo" target="_blank"
            >a small amount</a
          >
          via PayPal if
          <a
            rel="nofollow"
            href="https://templatemo.com/tm-567-nomad-force"
            target="_parent"
            >Nomad Force Template</a
          >
          is useful for you. This will absolutely help us to keep creating
          better CSS templates for you. <br /><br />We provide you 100% free
          templates on TemplateMo website. Images are provided by FreePik and
          Unsplash websites.
        </p>
      </div>

      <div class="col-lg-6 col-12 mt-lg-3 mb-lg-5">
        <p data-aos="fade-up" data-aos-delay="500">
          This Bootstrap 5 layout is free to use for your business. You are
          allowed to edit it in any way you like. However, please do not
          redistribute this template ZIP file for a template download purpose on
          any other website such as Free CSS collections.
        </p>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3 col-12 p-0">
        <img
          src="{% static 'images/elena-rabkina-eVVzwsNhNf4-unsplash.jpg' %}"
          class="img-fluid about-image"
          alt=""
        />
      </div>

      <div class="col-lg-3 col-12 bg-dark">
        <div
          class="d-flex flex-column flex-wrap justify-content-center h-100 py-5 px-4 pt-lg-4 pb-lg-0"
        >
          <h3 class="text-white mb-3" data-aos="fade-up">
            We’re - idealists and strategic thinkers.
          </h3>

          <p class="text-secondary-white-color" data-aos="fade-up">
            Over six years in the video business
          </p>

          <div class="mt-3 custom-links">
            <a
              href="#news"
              class="text-white custom-link"
              data-aos="zoom-in"
              data-aos-delay="100"
              >Read News & Events</a
            >

            <a
              href="#contact"
              class="text-white custom-link"
              data-aos="zoom-in"
              data-aos-delay="300"
              >Work with Us</a
            >
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-12 p-0">
        <section
          id="myCarousel"
          class="carousel slide carousel-fade"
          data-bs-ride="carousel"
        >
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img
                src="{% static 'images/people/studio-shot-beautiful-happy-retired-caucasian-female-with-pixie-hairdo-crossing-arms-her-chest-having-confident-look-smiling-broadly.jpg' %}"
                class="img-fluid team-image"
                alt=""
              />

              <div class="team-thumb bg-warning">
                <h3 class="text-white mb-0">Susane R.</h3>

                <p class="text-secondary-white-color mb-0">Founding Partner</p>
              </div>
            </div>

            <div class="carousel-item">
              <img
                src="{% static 'images/people/project-leder-with-disabilities-looking-front-sitting-immobilized-wheelchair-business-office-room.jpg' %}"
                class="img-fluid team-image"
                alt=""
              />

              <div class="team-thumb bg-primary">
                <h3 class="text-white mb-0">Morgan S.</h3>

                <p class="text-secondary-white-color mb-0">CEO & Investor</p>
              </div>
            </div>

            <div class="carousel-item">
              <img
                src="{% static 'images/people/asia-business-woman-feeling-happy-smiling-looking-camera-while-relax-home-office.jpg' %}"
                class="img-fluid team-image"
                alt=""
              />

              <div class="team-thumb bg-success">
                <h3 class="text-white mb-0">Naomi W.</h3>

                <p class="text-secondary-white-color mb-0">Art Director</p>
              </div>
            </div>

            <div class="carousel-item">
              <img
                src="{% static 'images/people/happy-african-american-professional-manager-smiling-looking-camera-headshot-portrait.jpg' %}"
                class="img-fluid team-image"
                alt=""
              />

              <div class="team-thumb bg-info">
                <h3 class="text-white mb-0">Robinson H.</h3>

                <p class="text-secondary-white-color mb-0">Sales & Marketing</p>
              </div>
            </div>

            <div class="carousel-item">
              <img
                src="{% static 'images/people/working-business-lady.jpg' %}"
                class="img-fluid team-image"
                alt=""
              />

              <div class="team-thumb bg-danger">
                <h3 class="text-white mb-0">Jane M.</h3>

                <p class="text-secondary-white-color mb-0">
                  Project Management
                </p>
              </div>
            </div>
          </div>

          <button
            class="carousel-control-prev"
            type="button"
            data-bs-target="#myCarousel"
            data-bs-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>

            <span class="visually-hidden">Previous</span>
          </button>

          <button
            class="carousel-control-next"
            type="button"
            data-bs-target="#myCarousel"
            data-bs-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>

            <span class="visually-hidden">Next</span>
          </button>
        </section>
      </div>
    </div>
  </div>
</section>

templates/includes/contact.html
<style type="text/css">
  input {
    color: #555 !important;
  }
  .form_c:focus {
    outline: #FFC107 solid 3px;
    transition: 0.5s all ease;
    border: none;
    box-shadow: none;
  }
  .form_c{
    transition: .1s outline ease !important;
  }
</style>
<section class="contact section-padding" id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-7 col-12 mx-auto">
        <h2 style="font-size: 35px !important;" class="mb-5 text-center" data-aos="fade-up">
          Hoziroq ariza bering, va biz siz bilan bog'lanamiz
        </h2>

        <form
          action="#"
          method="post"
          class="contact-form"
          role="form"
          data-aos="fade-up"
        >
        {% load widget_tweaks %}
        {% csrf_token %}
          <div class="row">
            <div class="col-lg-6 col-6">
              <label for="name" class="form-label"
                >To'liq ism familiya <sup class="text-danger">*</sup></label
              >

              {% render_field form.full_name type="text" class="form-control form_c" placeholder="Toliq ism familiya" %}
            </div>

            <div class="col-lg-6 col-6">
              <label for="number" class="form-label"
                >Shahsiy raqam <sup class="text-danger">*</sup></label
              >

               {% render_field form.own_phone type="number" class="form-control form_c" %}
            </div>
            <div class="col-lg-6 col-6 mt-5">
              <label for="number" class="form-label"
                >Qo'shimcha raqam <sup class="text-danger">*</sup></label
              >

               {% render_field form.extra_phone type="number" class="form-control form_c" %}
            </div>
            <div class="col-lg-6 col-6 mt-5">
              <label for="number" class="form-label"
                >Yo'nalishni tanlang <sup class="text-danger">*</sup></label
              >

               {% render_field form.category type="text" class="form-control form_c" %}
            </div>

            <div class="col-12 my-4 mt-5">
              <label for="message" class="form-label">Aniq qanday maqsad bor(Iltimos qisqa va lo'nda bo'lsin)</label>

              {% render_field form.message type="text" class="form-control form_c" placeholder="Men frontend dasturchi bolmoqchiman" %}
            </div>

<!--             <div class="col-12">
              <label for="services" class="form-label"
                >Services<sup class="text-danger">*</sup></label
              >
            </div> -->

<!--             <div class="col-lg-4 col-12">
              <div class="form-check">
                <input
                  type="checkbox"
                  id="checkbox1"
                  name="checkbox1"
                  class="form-check-input"
                />

                <label class="form-check-label" for="checkbox1">Branding</label>
              </div>
            </div>

            <div class="col-lg-4 col-12 my-2 my-lg-0">
              <div class="form-check">
                <input
                  type="checkbox"
                  id="checkbox2"
                  name="checkbox2"
                  class="form-check-input"
                />

                <label class="form-check-label" for="checkbox2"
                  >Digital Experiences</label
                >
              </div>
            </div>

            <div class="col-lg-4 col-12">
              <div class="form-check">
                <input
                  type="checkbox"
                  id="checkbox3"
                  name="checkbox3"
                  class="form-check-input"
                />

                <label class="form-check-label" for="checkbox3"
                  >Web Development</label
                >
              </div>
            </div> -->
          </div>

          <div class="col-lg-5 col-12 mx-auto mt-5">
            <button type="submit" class="form-control">Jo'natmoq</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

templates/includes/footer.html
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h5 class="text-white">
                    <i class="bi-geo-alt-fill me-2"></i>
                    Andijon Viloyati, Izboskan tuman
                </h5>
                <a href="mailto:info@company.com" class="custom-link mt-3 mb-5">
                    info_ithacademy@email.com
                </a>
            </div>
            <div class="col-6">
                <span class="copyright-text mb-0">Copyright © ITHA Academy</span>
                <br><br>Design: <a href="https://github.com/hwandev12/" target="_blank">Husan Ahmedov</a><br><br>
                Distributed By: <a href="https://github.com/ziyotech" target="_blank">ITHA Members</a>
                </p>
            </div>
            <div class="col-lg-3 col-5 ms-auto">
                <ul class="social-icon">
                    <li><a href="#" class="social-icon-link bi-facebook"></a></li>
                    <li><a href="#" class="social-icon-link bi-twitter"></a></li>
                    <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>
                    <li><a href="#" class="social-icon-link bi-instagram"></a></li>
                    <li><a href="#" class="social-icon-link bi-youtube"></a></li>
                </ul>
            </div>
        </div>
        </section>
</footer>

templates/includes/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light shadow-lg">
  <div class="container">
    <a class="navbar-brand" href="{% url 'company:home' %}">
      <img style="width: 130px;" src="{% static 'images/logo.png' %}">
    </a>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#hero">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#about">Our Studio</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#portfolio">Portfolio</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#news">News & Events</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#contact">Contact Us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/portfolio.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<section class="section-padding" id="portfolio">
    <div class="container">
        <div class="row">
            <div>
                <h2 class="mb-5 text-center" data-aos="fade-up">Portfolio</h2>
            </div>
            <div class="col-lg-12 big" style="display: flex; margin-right: 10px !important; justify-content: space-between; flex-wrap: wrap;">
                {% for portfolio in portfolios %}
                <div class="portfolio-thumb cards mb-4" data-aos="fade-up" style="width: 500px;">
                    <a href="#">
                        <img src="{{ portfolio.portfolio_image.url }}" class="img-fluid portfolio-image" alt="" />
                    </a>
                    <div class="portfolio-info">
                        <h4 class="portfolio-title mb-0">{{ portfolio.portfolio_heading }}</h4>
                        <p class="text-danger">{{ portfolio.portfolio_subheading }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="read">
                <a class="btn btn-outline-info" href="#">Read more<i class="fa-solid fa-arrow-right"></i></a>
            </div>
        </div>
    </div>
</section>

templates/includes/video.html
{% load static %}
<style type="text/css">
    #text2 {
        /*animation: blink-caret 0.75s step-end infinite;*/
        display: inline-block !important;
        font-weight: bold;
        width: 100px;
    }

    @keyframes blink-caret {
        0% {
            border-color: transparent
        }

        50% {
            border-right: 2px solid #fff;
        }
    }

    .caret_writer {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    @media screen and (max-width: 700px) {
        .caret_writer {
            flex-direction: column !important;
        }

        .caret_writer p {
            position: absolute;
            top: 130px;
            height: 40px;
            font-size: 25px !important;
        }
    }

    @media screen and (min-width: 700px) and (max-width: 1000px) {
        .caret_writer {
            flex-direction: column !important;
        }

        .caret_writer p {
            position: absolute;
            top: 130px;
            height: 40px;
            font-size: 35px !important;
        }
    }
</style>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;700;900&display=swap"
    rel="stylesheet" />
<link rel="stylesheet" href="{% static 'css/header.css' %}" rel="stylesheet" />
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet" />
<link rel="stylesheet" href="css/magnific-popup.css' %}" />
<link href="{% static 'css/aos.css' %}" rel="stylesheet" />
<link href="{% static 'css/templatemo-nomad-force.css' %}" rel="stylesheet" />
<section class="hero" id="hero">
    <div class="heroText">
        <!-- <img style="width: 130px;" src="{% static 'images/logo.png' %}"> -->
        <div class="caret_writer">
            <h1 class="text-white mt-5 mb-lg-4 img-header" style="font-size: 40px;" data-aos="zoom-in"
                data-aos-delay="800">
                <img style="
      width: 400px;
      position: relative;
      top: -38px;
      " src="{% static 'images/logo.png' %}">
            </h1>
            <p id="text2" style="display: inline; font-size: 40px;"></p>
        </div>
        <p class="text-secondary-white-color" data-aos-delay="1000">
            IT Housega
            <a href="#contact"><strong class="custom-underline">qabul</strong></a>
            davom etmoqda
        </p>
    </div>
    <div class="videoWrapper">
        <video autoplay="" loop="" muted="" class="custom-video">
            <source src="" type="video/mp4" />
            Your browser does not support the video tag.
        </video>
    </div>
    <div class="overlay"></div>
</section>
<!-- JAVASCRIPT FILES -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/magnific-popup-options.js' %}"></script>
<script src="{% static 'js/scrollspy.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script>
    var words = ["Academy", "Education"]
    var colors = ["#fff", "#fff", "#fff"]


    var counter = 0;
    var currentIndex = getRandomInt(0, words.length - 1);

    var text = document.getElementById("text2");

    var stepInterval = setInterval(() => { step(); }, 200);
    var delInterval = null;
    var delTimeout = null;

    function getRandomInt(min, max) {
        min = Math.ceil(min);
        max = Math.floor(max);
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

    function delIntervalCallback() {
        delInterval = setInterval(() => { del(); }, 100);
        clearTimeout(delTimeout);
    }

    function del() {
        if (counter == 0) {
            let newIndex = getRandomInt(0, words.length - 1);
            while (newIndex == currentIndex) {
                newIndex = getRandomInt(0, words.length - 1);
            }
            currentIndex = newIndex;
            clearInterval(delInterval);
            stepInterval = setInterval(() => { step(); }, 200);
        } else {
            text.textContent = text.textContent.slice(0, -1)
            counter--;
        }
    }

    function step() {
        if (counter >= words[currentIndex].length) {
            clearInterval(stepInterval);
            delTimeout = setTimeout(() => { delIntervalCallback(); }, 2000);
        } else {
            text.textContent += words[currentIndex][counter];
            text.style.color = colors[currentIndex];
            counter++;
        }
    }
</script>

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home - {% endblock title %}</title>
</head>
<body>
    <main>
        {% include 'includes/video.html' %}
        {% include 'includes/navigation.html' %}
        {% block content %}
        {% endblock content %}
    </main>
    {% include 'includes/footer.html' %}
</body>
</html>

templates/pages/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<style type="text/css">
.messages {
    margin-top: 30px;
    margin-left: 30px;
}

.messages_section {
    width: 550px;
    border: 1px solid #999;
    padding: 10px 20px;
}

.messages h2 {
    margin-bottom: 30px !important;
}

.messages_section a {
    display: inline-block;
    text-align: center;
    width: 100%;
}

.messages_section table {
    margin-top: 20px;
}

.messages_section table th,
td {
    /*padding-right: 150px !important;*/
    /*margin-right: 60px !important;*/
    /*border: 2px solid red;*/
    border-bottom: 1px solid rgba(1, 1, 1, 0.4);
    padding: 10px 50px;
}
</style>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'company:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <section class="messages">
        <h2>Messages:</h2>
        <hr>
        <div class="messages_section">
            <a class="btn btn-primary" href="#">Apply Message</a>
            <table>
                <tr class="bordered">
                    <th>Users</th>
                    <th>Type</th>
                    <th></th>
                    <hr>
                </tr>
                {% for y in contact %}
                <tr class="contact_objects">
                    <td>{{ y.full_name }}</td>
                    <td class="category_contact">{{ y.category }}<i class="fa-solid fa-key"></i></td>
                    <td><a class="btn btn-info" href="#">View</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>

</html>

templates/pages/home.html
{% extends 'layouts/base.html' %}

{% block content %}
    <!-- {% include 'includes/about.html' %} -->
    {% include 'includes/portfolio.html' %}
    {% include 'includes/contact.html' %}
{% endblock content %}